version: "3"
services:
  postgres:
    container_name: gama-lab-playlistDB
    image: postgres:alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: development
      POSTGRES_DB: playlist
      PGDATA: /var/lib/postgres