version: '3.1'
services:
  postgres:
    container_name: social-dev
    image: postgres:alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: development
      POSTGRES_DB: mydb
      PGDATA: /var/lib/postgres
