version: '3.1'
services:
  db:
    image: mysql
    container_name: gama-lab-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydb
    ports:
      - "3306:3306"
